// import { arrondirCote, arrondirTemperature }  from "../utils/CalculProduction"

test('should round the level measure and return dm and mm measures', () => { 

   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")

   //  expect(arrondirCote(90)).toBe({coteDm : 0 , coteMm : 90})
   //  expect(arrondirCote(100)).toBe({coteDm : 1 , coteMm : 0})
   //  expect(arrondirCote(103)).toBe({coteDm : 1 , coteMm : 0})
   //  expect(arrondirCote(1003)).toBe({coteDm : 10 , coteMm : 0})
   //  expect(arrondirCote(2113)).toBe({coteDm : 21 , coteMm : 10})
   //  expect(arrondirCote(2123)).toBe({coteDm : 21 , coteMm : 20})
   //  expect(arrondirCote(2133)).toBe({coteDm : 21 , coteMm : 30})
   //  expect(arrondirCote(2143)).toBe({coteDm : 21 , coteMm : 40})

 })

 test('should round the temperature and return it', () => { 

   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")

   //  expect(arrondirTemperature(0)).toBe(0)
   //  expect(arrondirTemperature(10)).toBe(10)
   //  expect(arrondirTemperature(10.14)).toBe(10)
   //  expect(arrondirTemperature(10.27)).toBe(10.5)
   //  expect(arrondirTemperature(10.50)).toBe(10.5)
   //  expect(arrondirTemperature(10.67)).toBe(10.5)
   //  expect(arrondirTemperature(10.78)).toBe(11)
   //  expect(arrondirTemperature(10.98)).toBe(11)
 
 })

 test('should calculate the correction coefficient correctly', () => { 
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
 })

test('should calculate the correction coefficient by the iterpolation method correctly', () => { 
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
})

test('should calculate the standard volume of oil correctly', () => { 
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
})

test('should calculate the Bac operation results correctly', () => { 
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
})

test('should calculate the Unit daily production correctly', () => { 
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
})

test('should calculate the Region daily production correctly', () => { 
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
})

test('should calculate the Oil well daily production correctly', () => {
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s") 

})

test('should calculate the Oil well daily corrected production correctly', () => { 
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
})

test('should calculate the perimeter daily production correctly', () => { 
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
   console.log("asklsakaslk s")
})